name: "企业微信消息推送"
version: "0.0.5"
slug: "wenotify_tianxin"
description: "使用企业号推送微信消息，基于天行数据api"
url: "https://github.com/xswxm/hassio-addons/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
options:
  api: "saylove"
  key: "你的apikey"
  push_time: "12:00:00"
  corpid: "企业微信corpid"
  corpsecret: "企业微信corpsecret"
  agentid: "企业微信agentid"
  touser: "@all"
  http_proxy: "HTTP代理服务"
  https_proxy: "HTTPS代理服务"
schema:
  api: str
  key: str
  push_time: str
  corpid: str
  corpsecret: str
  agentid: str
  touser: str
  http_proxy: str
  https_proxy: str